// Real browser tests against the disposable WordPress installation. Not shipped.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require = createRequire(new URL('../.cache/tools/package.json', import.meta.url));
const { chromium: playwright } = require('playwright');
const chromeModule = require('@sparticuz/chromium');
const chromium = chromeModule.default || chromeModule;
const fixture = JSON.parse(fs.readFileSync(new URL('../.cache/runtime/fixture-manifest.json', import.meta.url)));
const base = process.env.HAMRAH_TEST_URL || 'http://127.0.0.1:8080';
const results = [];
const check = (value, name) => { assert.ok(value, name); results.push({name, passed:true}); };
const browser = await playwright.launch({ executablePath: await chromium.executablePath(), args: chromium.args, headless:true, env:{...process.env, LD_LIBRARY_PATH:new URL('../.cache/tools/chromium-libs/lib', import.meta.url).pathname} });
const context = await browser.newContext({viewport:{width:1440,height:1100}});
const page = await context.newPage();
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
const visit = async path => { const r=await page.goto(base+path,{waitUntil:'networkidle'}); check(r.status()<400,'HTTP '+path); };
const ids = async () => page.locator('.hs-catalog ul.products > li.product').evaluateAll(nodes=>nodes.map(node=>Number(node.className.match(/\bpost-(\d+)/)?.[1])).filter(Boolean));
const waitCatalog = async () => { await page.waitForFunction(()=>!document.querySelector('[data-hs-shop-shell].is-loading')); };
try {
  await visit('/shop/');
  check(await page.locator('html').getAttribute('dir')==='rtl','Persian document direction');
  check((await ids()).length===6,'Published catalog visibility and missing-image products');
  check(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)),'Desktop has no horizontal overflow');
  await page.screenshot({path:new URL('../.cache/catalog-desktop.png',import.meta.url).pathname,fullPage:true});

  const blue=page.locator('input[name="hs_attr_hs-test-color[]"][value="hs-test-blue"]');
  const fetchBlue=page.waitForResponse(r=>r.url().includes('filter_hs-test-color=hs-test-blue') && r.request().headers()['x-hamrah-catalog']==='1');
  await blue.check(); await fetchBlue; await waitCatalog();
  check((await ids()).length===4,'AJAX global attribute filtering');
  check(page.url().includes('query_type_hs-test-color=or'),'Shareable native WooCommerce attribute URL');
  const multi=page.waitForResponse(r=>r.url().includes('hs-test-black') && r.request().headers()['x-hamrah-catalog']==='1');
  await page.locator('input[name="hs_attr_hs-test-color[]"][value="hs-test-black"]').check(); await multi; await waitCatalog();
  check((await ids()).length===5,'Multi-select OR filtering');
  await visit('/shop/?min_price=200000&max_price=300000');
  const priceIds=await ids();
  check(priceIds.length===3 && priceIds.includes(fixture.base) && priceIds.includes(fixture.sale),'Native WooCommerce price filtering');
  await visit('/shop/?hs_sale=1'); check((await ids()).length===1 && (await ids())[0]===fixture.sale,'Indexed sale filter');
  await visit('/shop/?hs_stock=outofstock'); check((await ids()).length===1 && (await ids())[0]===fixture.out,'Indexed stock filter');
  await visit('/shop/?hs_brand=hs-test-brand'); check((await ids()).length===3,'Native product brand filtering');
  await visit('/shop/?hs_categories='+fixture.category); check((await ids()).length===5,'Hierarchical category includes child products');
  await visit('/shop/?orderby=price'); check((await ids())[0]===fixture.out,'Native price ascending sort');
  await visit('/shop/?orderby=price-desc'); check((await ids())[0]===fixture.variable,'Native price descending sort');
  await visit('/shop/?orderby=hs_stock'); check((await ids()).at(-1)===fixture.out,'In-stock-first sort');
  await visit('/shop/?orderby=hs_sale'); check((await ids())[0]===fixture.sale,'Sale-first sort');
  await visit('/shop/?orderby=date'); check((await ids()).length===6,'Newest sort');
  await visit('/shop/?orderby=popularity'); check((await ids()).length===6,'Popularity sort');

  await visit('/shop/');
  const sorted=page.waitForResponse(r=>r.url().includes('orderby=hs_sale') && r.request().headers()['x-hamrah-catalog']==='1');
  await page.locator('.woocommerce-ordering select').selectOption('hs_sale'); await sorted; await waitCatalog();
  check((await ids())[0]===fixture.sale,'Sorting uses AJAX without a page navigation');
  await page.locator('#hs-search-header').fill('HS-TEST-BASE');
  await page.locator('[data-hs-search-results] a').waitFor();
  check((await page.locator('[data-hs-search-results] a').count())===1,'Live SKU search returns real data');
  await page.locator('#hs-search-header').press('Escape');
  await visit('/?s=HS-TEST-VAR-01&post_type=product');
  check(((await ids()).length===1 && (await ids())[0]===fixture.variable) || await page.locator('#product-'+fixture.variable).count()===1,'Full variation SKU search / native single-result redirect');
  await visit('/?s=%D9%BE%D8%A7%DB%8C%D9%87&post_type=product');
  check((await ids()).includes(fixture.base) || await page.locator('#product-'+fixture.base).count()===1,'Full Persian title search');
  await visit('/?s=%D9%85%D8%AD%D8%B5%D9%88%D9%84&post_type=product');
  check((await ids()).length>=6,'Native multiple-product search results archive');

  await visit('/shop/');
  await page.locator(`[data-hs-wishlist="${fixture.base}"]`).click();
  check(await page.locator(`[data-hs-wishlist="${fixture.base}"]`).getAttribute('aria-pressed')==='true','Persistent wishlist toggle');
  await visit('/wishlist/'); await page.locator('.hs-wishlist-card').waitFor();
  check((await page.locator('.hs-wishlist-card').count())===1,'Wishlist renders real WooCommerce product');
  await page.locator('.hs-wishlist-remove').click();
  check((await page.locator('.hs-wishlist-card').count())===0,'Wishlist remove and empty state');

  await page.setViewportSize({width:390,height:844}); await visit('/shop/');
  check(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)),'Mobile catalog has no horizontal overflow');
  await page.locator('[data-hs-open-filters]').click(); check(await page.locator('#hs-filter-dialog').evaluate(x=>x.open),'Mobile native modal filter drawer');
  await page.locator('#hs-filter-dialog input[value="hs-test-blue"]').check();
  await page.locator('#hs-filter-dialog input[value="hs-test-black"]').check();
  const applied=page.waitForResponse(r=>r.request().headers()['x-hamrah-catalog']==='1');
  await page.locator('#hs-filter-dialog button[type=submit]').click(); await applied; await waitCatalog();
  check((await ids()).length===5,'Mobile multi-select apply');
  check(!(await page.locator('#hs-filter-dialog').evaluate(x=>x.open)),'Drawer closes after applying filters');
  await page.locator('[data-hs-dialog-open]').click();
  check(await page.locator('#hs-mobile-menu').evaluate(x=>x.open),'Mobile menu opens');
  await page.keyboard.press('Escape');
  check(!(await page.locator('#hs-mobile-menu').evaluate(x=>x.open)),'Keyboard Escape closes modal');
  await page.screenshot({path:new URL('../.cache/catalog-mobile.png',import.meta.url).pathname,fullPage:true});
  await visit('/shop/?hs_stock=outofstock&min_price=900000');
  check((await ids()).length===0 && await page.locator('.woocommerce-info').count()===1,'Empty filtered results are genuine');

  await page.setViewportSize({width:1440,height:1100});
  await visit('/?p='+fixture.out+'&post_type=product');
  check(await page.locator('.stock.out-of-stock').count()===1,'Out-of-stock product cannot be added');
  check(await page.locator('.woocommerce-product-gallery img.wp-post-image').first().evaluate(x=>x.complete && x.naturalWidth>0),'Missing-image icon is a valid local asset');
  await visit('/?p='+fixture.sale+'&post_type=product');
  check(await page.locator('.summary .price del').count()===1 && await page.locator('.summary .price ins').count()===1,'Real scheduled sale price rendering');
  await visit('/?p='+fixture.base+'&post_type=product');
  check(await page.locator('.summary .price del').count()===0,'No fabricated discount on a regular product');
  check(await page.locator('.woocommerce-product-gallery').count()===1,'Native gallery and lightbox integration');
  check(await page.locator('script[type="application/ld+json"]').count()>0,'Native WooCommerce product structured data');
  await page.locator('button[name="add-to-cart"]').click(); await page.waitForLoadState('networkidle');
  await visit(fixture.cart_path || '/cart/');
  check(await page.locator('.cart_item').count()===1,'Native add to cart and real cart line item');
  await page.locator('.cart_item input.qty').fill('2');
  await page.locator('button[name="update_cart"]').click();
  await page.waitForFunction(()=>document.querySelector('.cart_item input.qty')?.value==='2'&&!document.querySelector('.woocommerce-cart-form .blockOverlay'));
  check(await page.locator('.cart_item input.qty').inputValue()==='2','Native cart quantity update');

  await visit('/?p='+fixture.variable+'&post_type=product');
  await page.locator('select[name="attribute_pa_hs-test-color"]').selectOption('hs-test-blue');
  await page.waitForFunction(()=>!document.querySelector('.hs-buy-now').classList.contains('disabled'));
  await page.locator('.hs-buy-now').click(); await page.waitForURL(/checkout/); await page.waitForLoadState('networkidle');
  check(page.url().includes('checkout'),'Variation buy-now performs real add-to-cart and redirect');
  check(await page.locator('.woocommerce-checkout-review-order-table .cart_item').count()===2,'Buy-now preserves the existing cart');
  await page.locator('#billing_first_name').fill('آزمون');
  await page.locator('#billing_last_name').fill('موقت');
  await page.locator('#billing_country').selectOption('IR');
  await page.locator('#billing_address_1').fill('نشانی آزمون موقت');
  await page.locator('#billing_city').fill('تهران');
  await page.locator('#billing_state').selectOption('THR');
  await page.locator('#billing_postcode').fill('۱۲۳۴۵۶۷۸۹۰');
  await page.locator('#billing_phone').fill('۰۹۱۲۳۴۵۶۷۸۹');
  await page.locator('#billing_email').fill('hs-checkout@example.test');
  if (await page.locator('#ship-to-different-address-checkbox').count()) await page.locator('#ship-to-different-address-checkbox').uncheck();
  await page.waitForFunction(()=>!document.querySelector('#order_review .blockOverlay'));
  check(await page.locator('#payment_method_cod').count()===1,'Checkout uses a real native gateway');
  await page.locator('#payment_method_cod').check();
  await page.locator('#place_order').click();
  await page.waitForURL(/order-received/, {timeout:45000});
  check(await page.locator('.woocommerce-order').count()===1,'Real checkout creates an order and receipt');
  await page.setViewportSize({width:390,height:844});
  check(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)),'Mobile receipt has no overflow');

  await visit('/my-account/');
  const email='hs-register-'+Date.now()+'@example.test';
  await page.locator('#reg_email').fill(email);
  await page.locator('#reg_password').fill('DisposableTest!4720secure');
  if (await page.locator('#reg_username').count()) await page.locator('#reg_username').fill('hs-customer-'+Date.now());
  await page.waitForFunction(()=>typeof window.zxcvbn==='function');
  await page.locator('#reg_password').press('Tab');
  await Promise.all([page.waitForResponse(r=>r.request().method()==='POST'&&r.url().includes('my-account')),page.locator('button[name="register"]').click()]); await page.waitForLoadState('networkidle');
  check(await page.locator('.woocommerce-MyAccount-navigation').count()===1,'Real customer registration and account panel');
  check(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)),'Mobile account panel has no overflow');
  check(errors.length===0,'No browser JavaScript runtime errors');

  // Admin authentication and responsive custom settings remain native WordPress.
  const adminContext=await browser.newContext({viewport:{width:390,height:844}});
  const admin=await adminContext.newPage();
  const credentials=JSON.parse(fs.readFileSync(new URL('../.cache/runtime/admin.json',import.meta.url)));
  await admin.goto(base+'/wp-login.php');
  await admin.locator('#user_login').fill(credentials.username); await admin.locator('#user_pass').fill(credentials.password);
  await admin.locator('#wp-submit').click(); await admin.waitForURL(/wp-admin/);
  check(admin.url().includes('wp-admin'),'Native WordPress administrator login');
  await admin.goto(base+'/wp-admin/admin.php?page=hamrah-shop',{waitUntil:'networkidle'});
  check(await admin.locator('.hs-admin').count()===1,'Capability-protected settings page exists');
  check(!(await admin.evaluate(()=>document.documentElement.scrollWidth>innerWidth)),'Custom admin settings fit mobile');
  await admin.screenshot({path:new URL('../.cache/admin-mobile.png',import.meta.url).pathname,fullPage:true});
} finally {
  fs.writeFileSync(new URL('../.cache/browser-results.json',import.meta.url),JSON.stringify({checks:results,jsErrors:errors},null,2));
  console.log(JSON.stringify({passed:results.length,jsErrors:errors},null,2));
  await browser.close();
}
